### ISSUE TITLE
Excerpt_length limiteren naar max 3 regels voor stages/studenten

### ISSUE THREAD

**Issue by kyrahendriks** [bartvanderwal/on-stage#14]
Reden hiervoor is dat je geen enorme artikelen wilt hebben staan op de homepagina, je wilt dat de samenvatting (excerpt) ook daadwerkelijk een samenvatting is.

**Comment by bartvanderwal** [comment]
Goed bezig @kyrahendriks !

Ik ga vanmiddag naar de issues kijken en een paar oppakken. Standaard limiteert Wordpress de excerpt al naar 55 woorden. 

Je kunt hier standaard NIET het aantal regels instellen maar alleen aantal woorden. Aantal regels hangt natuurlijk ook af van beeldscherm breedte en gebruikte font (grootte). En natuurlijk hoe lang de woorden gemiddeld zijn (en of je veel smalle letters gebruikt zoals `l` of juist veel breder, zoals 'm' (gezien we geen monspace font gebruiken).

Op mijn iPhone SE zijn 20 a 25 woorden al drie regels in portrait mode. In landscape gaat dit naar ca. 40 woorden.
Ik stel voor excerpt dan van default 55 naar op max 25 a 30 woorden te zetten. Even kijken naar voorbeelden uit jouw ontwerp.

Evt. kun je boven wijziging in wordpress in CSS via `text-overflow: ellipsis;` o.i.d. het ook wel instellen dat tekst wordt ingekort als het toch langer uitpakt dan 3 regels. Dan heb je ook een `overflow: hidden` nodig geloof ik:
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/

Wordpress pakt trouwens ook bij lege excerpt automatisch de 1e (max) 55 woorden uit de 'content' veld als excerpt als je het excerpt veld leeglaat. Ik weet niet of dat op edit scherm al duidelijk is;

>If Excerpt is empty, WordPress automatically creates an excerpt using the first 55 words of the post.

Bron: https://wordpress.org/support/article/excerpt/
