### ISSUE TITLE
Verwijder Hallo wereld van homepagina

### ISSUE THREAD

**Issue by kyrahendriks** [bartvanderwal/on-stage#15]

**Comment by bartvanderwal** [comment]
Done.

De 'Hello World' kwam uit de de [`the_title()`](https://developer.wordpress.org/reference/functions/the_title/) aanroep die in de `header.php` in het onstage theme stond. Die heb ik verwijderd.

Deze pakt de titel van de 1e post die standaard in nieuwe Wordpress install staat.
